# Generated by Django 5.1 on 2024-10-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ('titulo',)},
        ),
    ]
