# Generated by Django 5.1 on 2024-11-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_colecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
    ]
