# Generated by Django 5.1 on 2024-11-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ('nome',)},
        ),
    ]
